baseURL: "https://react-ws.github.io/"
languageCode: "en-us"
title: "REACT: REsponsible Affective CompuTing"

enableEmoji: true

module:
  imports:
  - path: "github.com/willfaught/paige"

paige:
  analytics:
    disabled: true
  comments:
    disabled: true
  color: "#0d6efd"
  math: true
  menu:
    breakpoint: "sm" # Bootstrap breakpoint at which to display all menu items
    style: "pills" # Must be "links" or "pills"
  search:
    hide_page: true

# languages:
#   en:
#     menu:
#       main:
#       - identifier: "2023"
#         name: "2023"
#         url: "/2023"
#         weight: 20
#     weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true